taskomatic/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("users", views.users_view, name="users"),
    path("login", views.login_view, name="login"),
    path("register", views.register, name="register"),
    path("logout", views.logout_view, name="logout"),
    path("newProject", views.new_project, name="newProject"),
    path("editProject", views.edit_project, name="editProject"),
    path("deleteProject", views.delete_project, name="deleteProject"),
    path("handleTasks/<str:action>/<int:pk>", views.handle_tasks, name="handleTasks"),
    path("handleTasks/<str:action>", views.handle_tasks, name="handleTasks"),
    path("handleInventory/<str:action>/<int:pk>", views.handle_inventory, name="handleInventory"),
    path("handleInventory/<str:action>", views.handle_inventory, name="handleInventory"),
    path("project/<str:pk>/", views.project_view, name="projectPage"),
    path("accept/<str:pk>/", views.accept_contact, name="acceptContact"),
    path("reject/<str:pk>/", views.reject_contact, name="rejectContact"),
    path("users/<str:pk>/", views.add_contact, name="addContact"),
    path("members/<int:projectId>", views.add_member, name="addMember"),
    path("dismiss", views.dismiss_notification, name="dismiss")
]

taskomaticFinalProjectCs50w/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("taskomatic.urls")),
]

taskomatic/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator, MaxValueValidator

class User(AbstractUser):
    pass

class Project(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    owner = models.CharField(max_length=80)
    projectName = models.CharField(max_length=160)
    projectDescription = models.CharField(max_length=350)
    hasDeadline = models.BooleanField(default=False)
    hasInventory = models.BooleanField(default=False)
    hasTasks = models.BooleanField(default=False)
    creationDate = models.DateField(null=True, blank=True)
    deadlineDate = models.DateField(null=True, blank=True)

    def __str__(self):
        return f"{self.projectName} created by {self.user}"

class Member(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
class Inventory(models.Model):
    UNITS_CATEGORIES = [
        ('UNIT', 'unit(s)'),
        ('%', 'percent'),
        ('KG', 'kilogram(s)'),
        ('CM', 'centimeter(s)')
    ]
    projectId = models.ForeignKey(Project, on_delete=models.CASCADE)
    itemName = models.CharField(max_length=160)
    itemDescription = models.CharField(max_length=350)
    itemQty = models.PositiveIntegerField(default=0, validators=[MinValueValidator(0)])
    itemUnit = models.CharField(max_length=20, choices=UNITS_CATEGORIES, default=UNITS_CATEGORIES[0][0])
    itemLimitAlert = models.IntegerField(null=True, blank=True)

class Tasks(models.Model):
    PRIORITY_LEVELS = [tuple([x,x]) for x in range(1,11)]

    projectId = models.ForeignKey(Project, on_delete=models.CASCADE)
    taskCreator = models.CharField(max_length=80)
    taskName = models.CharField(max_length=160)
    taskDescription = models.CharField(max_length=350)
    taskCompletion = models.BooleanField(default=False)
    taskDeadline = models.DateField(null=True, blank=True)
    taskImportance = models.PositiveIntegerField(default=PRIORITY_LEVELS[0], choices=PRIORITY_LEVELS, validators=[MinValueValidator(1), MaxValueValidator(10)])
    taskLimitAlert = models.DateField(null=True, blank=True)
    taskCreationDate = models.DateField(null=True, blank=True)

class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Project, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    # participants =
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    
class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.body[0:50]

class Relationship(models.Model):
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('accepted', 'Accepted'),
        ('rejected', 'Rejected'),
    ]

    from_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='from_user')
    to_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='to_user')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='pending')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('from_user', 'to_user')

    def __str__(self):
        return f"{self.from_user} | {self.to_user} | {self.status}" 

class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    notification = models.CharField(max_length=100)

class Comment(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.CharField(max_length=280)
    date = models.DateField()
    time = models.TimeField()

taskomatic/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.db.models import Q
from datetime import datetime
from .forms import ProjectForm, TaskForm, InventoryForm, CompletionTaskForm, CommentForm
import json

from .models import User, Project, Tasks, Inventory, Relationship, Member, Notification, Comment


def index(request):
    if request.user.is_authenticated:

        # Retrieve relevant data
        currentUserId = request.user.id
        currentUser = User.objects.get(id=currentUserId)
        projects = Project.objects.filter(user=currentUser).order_by('-creationDate')
        contacts = Relationship.objects.filter(Q(from_user=currentUser) | Q(to_user=currentUser), ~Q(status='rejected'))
        contactRequests = Relationship.objects.filter(Q(to_user=currentUser), Q(status="pending"))
        memberProjects = Member.objects.filter(user=currentUser)
        notifications = Notification.objects.filter(user=currentUser)

        # Create a context dictionary with the retrieved data
        context = {
            "projects": projects,
            "memberProjects": memberProjects,
            "contacts": contacts,
            "contactRequests": contactRequests,
            "notifications": notifications 
        }

        return render(request, "taskomatic/index.html", context)
    return render(request, "taskomatic/index.html")


def users_view(request):

    # Retrieve relevant data
    q = request.GET.get('q', '')
    currentUserId = request.user.id
    currentUser = User.objects.get(id=currentUserId)
    users = User.objects.filter(Q(username__icontains=q), ~Q(username=currentUser))
    relationship = Relationship.objects.filter(Q(from_user=currentUser) | Q(to_user=currentUser))

    # Create dictionaries and store the relationship status (accepted or pending) for each user
    acceptedRelationshipStatus = {}
    pendingRelationshipStatus = {}
    for relation in relationship:
        if relation.status == 'pending':
            if currentUser == relation.from_user:
                user = str(relation.to_user)
                pendingRelationshipStatus[user] = relation.status
            elif currentUser == relation.to_user:
                user = str(relation.from_user)
                pendingRelationshipStatus[user] = relation.status
        elif relation.status == 'accepted':
            if currentUser == relation.from_user:
                user = str(relation.to_user)
                acceptedRelationshipStatus[user] = relation.status
            elif currentUser == relation.to_user:
                user = str(relation.from_user)
                acceptedRelationshipStatus[user] = relation.status

    # Create a context dictionary with the retrieved data          
    context = {
        "users": users,
        "acceptedRelationshipStatus": acceptedRelationshipStatus,
        "pendingRelationshipStatus": pendingRelationshipStatus
    }

    return render(request, "taskomatic/users.html", context)


def add_contact(request, pk):

    # Get the user that the current user wants to add as a contact
    to_user = User.objects.get(id=pk)
    currentUserId = request.user.id
    from_user = User.objects.get(id=currentUserId)

    # Create a new Relationship object with a status of "pending"
    relationship = Relationship(from_user=from_user, to_user=to_user, status='pending')
    relationship.save()

    # Redirect the user back to the page they were on
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def accept_contact(request, pk):

    #Retrieve and Update the relationship
    relationshipToUpdate = Relationship.objects.get(id=pk)
    relationshipToUpdate.status = "accepted"
    relationshipToUpdate.save()

    return HttpResponseRedirect(reverse("index"))


def reject_contact(request, pk):

    #Retrieve and Update the relationship
    relationshipToUpdate = Relationship.objects.get(id=pk)
    relationshipToUpdate.status = "rejected"
    relationshipToUpdate.save()

    return HttpResponseRedirect(reverse("index"))


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "taskomatic/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "taskomatic/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":

        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "taskomatic/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "taskomatic/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "taskomatic/register.html")


def project_view(request, pk):

    # Retrieve relevant data
    project = Project.objects.get(id=pk)
    tasks = Tasks.objects.filter(projectId = pk)
    inventory = Inventory.objects.filter(projectId = pk)
    comments = Comment.objects.filter(project=project).order_by('-id')

    # Form for task completion checkboxes
    taskForms = []
    for task in tasks:
        taskFormInstance = CompletionTaskForm(instance=task, task_id=task.id)
        taskForms.append(taskFormInstance)

    if request.method == 'POST':
        form = CommentForm(request.POST)

        if form.is_valid():
            currentUserId = request.user.id
            currentUser = User.objects.get(id=currentUserId)  
            f = Comment(project=project, user=currentUser, comment=form.cleaned_data['comment'], date=datetime.now().strftime("%Y-%m-%d"), time=datetime.now().strftime("%H:%M"))
            f.save()   

    # Create a context dictionary with the retrieved data
    context = {
        'project': project,
        'tasks': tasks,
        'inventory': inventory,
        'comments': comments,
        'taskForm': TaskForm(),
        'taskForms': taskForms,
        'inventoryForm': InventoryForm(),
        'form': CommentForm()
    }

    return render(request, "taskomatic/projectPage.html", context)


def new_project(request):
    user = User.objects.get(username=request.user)
    if request.method == "POST":
        print('NEW PAGE HERE')
        # Form validation
        form = ProjectForm(request.POST)
        if form.is_valid():
            f =  Project(user=form.cleaned_data['user'], owner=form.cleaned_data['owner'], projectName=form.cleaned_data['projectName'], 
                         projectDescription=form.cleaned_data['projectDescription'], hasTasks=form.cleaned_data['hasTasks'], 
                         hasInventory=form.cleaned_data['hasInventory'], hasDeadline=form.cleaned_data['hasDeadline'], 
                         deadlineDate=form.cleaned_data['deadlineDate'], creationDate=datetime.now().strftime("%Y-%m-%d"))
            f.save()
        else:
            print(form.errors)

        return HttpResponseRedirect(reverse("index"))
    return render(request, "taskomatic/newProject.html", {
        "form": ProjectForm(),
        "user": user
    })


def edit_project(request):
    if request.method == "POST":

        try: 

            # Update Project data
            projectCreationDate = request.POST['projectCreationDate']
            projectId = request.POST['projectId']
            projectInstance = Project.objects.get(id=projectId)
            form = ProjectForm(request.POST, instance=projectInstance)

            if form.is_valid():
                cleaned_data = form.cleaned_data
                projectInstance.user = cleaned_data['user']
                projectInstance.owner = cleaned_data['owner']
                projectInstance.projectName = cleaned_data['projectName']
                projectInstance.projectDescription = cleaned_data['projectDescription']
                projectInstance.hasDeadline = cleaned_data['hasDeadline']
                projectInstance.hasTasks = cleaned_data['hasTasks']
                projectInstance.hasInventory = cleaned_data['hasInventory']
                projectInstance.creationDate = projectCreationDate
                projectInstance.deadlineDate = cleaned_data['deadlineDate']
                projectInstance.save()
                print('Project Updated!')

            return HttpResponseRedirect(reverse("index"))   
        except:

            # Retrieve data and pre-populate form
            projectId = request.POST['projectId']
            projectInstance = Project.objects.get(id=projectId)
            form = ProjectForm(instance=projectInstance)
            creationDate = str(projectInstance.creationDate)
            print(creationDate)


taskomatic/templates/taskomatic/dashboard.html
<!-- When user press the ENTER button or log in, the user is redirected to the Dashboard. 
    Here they can visualize on-going projects and create new projects  
Or maybe just have everything on the index page using a conditional.-->

taskomatic/templates/taskomatic/inventoryForm.html
<form method="POST" action="{% url 'handleInventory' 'edit' %}" name="addInventoryForm" id="addInventoryForm">
    {% csrf_token %}
    <div class="p-3 inventoryModalForm">
        <input type="hidden" name="projectId" value="{{ currentProjectId }}">
        <input type="hidden" name="itemId" value="{{ currentItemId }}">
        {{ inventoryForm.itemName }}
        {{ inventoryForm.itemDescription }}
        <label for="id_itemQty" class="font-bold">Amount:</label>
        {{ inventoryForm.itemQty }}
        {{ inventoryForm.itemUnit }} <br>
        <label for="id_itemLimitAlert" class="font-bold">Restock Alert:</label>
        {{ inventoryForm.itemLimitAlert }}
    </div>
</form> 

taskomatic/templates/taskomatic/projectPage.html
{% extends "./layout.html" %}
{% load static %}

{% block body %}
    {% block script %}
<script defer src="{% static 'taskomatic/projectPage.js' %}"></script>
    {% endblock %}
<div id="projectPageMainContainer">
    <h2>
        {{ project.projectName }} &nbsp;
        <form style="display: inline-block;" method="POST" action="{% url 'editProject' %}" name="editForm">
            {% csrf_token %}
            <input type="hidden" name="projectId" id="projectId" value="{{ project.id }}">
            <i id="editIcon" class="fa-solid fa-pen-to-square cursor-pointer hover:text-sky-600" title="Edit Project"></i>
            <a href="{% url 'addMember' project.id %}">
                <i id="addMember" class="fa-solid fa-person-circle-plus cursor-pointer hover:text-sky-600" title="Add Member"></i>
            </a>
        </form>
    </h2>
    <p class="descriptiveParagraph">{{ project.projectDescription }}</p>
    <!-- "ADD TASK/INVENTORY" MODAL -->
    <div class="modal h-screen w-full fixed left-0 top-0 flex justify-center items-center bg-black bg-opacity-50 z-10 hidden">
        <div class="bg-white rounded shadow-lg lg:w-1/3 2/3">
            <div class="border-b px-4 py-2">
                <h3 class="modalTitle"></h3>
            </div>
            <form method="POST" action="{% url 'handleTasks' 'add' %}" name="addTaskForm" id="addTaskForm">
                {% csrf_token %}
                <div class="p-3 tasksModalForm">
                    <input type="hidden" name="projectId" value="{{ project.id }}">
                    <input type="hidden" name="taskCreator" value="{{ request.user }}">
                    {{ taskForm.taskName }}
                    {{ taskForm.taskDescription }}
                    <div class="p-1">
                        <label for="id_taskDeadline" class="font-bold">Deadline:</label>
                        {{ taskForm.taskDeadline }}
                    </div>
                    <div class="p-1">
                        <label for="id_taskLimitAlert" class="font-bold">Reminder:</label>
                        {{ taskForm.taskLimitAlert }}
                    </div>
                    <div class="p-1">
                        <label for="id_taskImportance" class="font-bold">Priority:</label>
                        {{ taskForm.taskImportance }} <span class="font-light text-sm italic">1 (Low) - 10 (High)</span>
                    </div>
                </div>
            </form>
            <form method="POST" action="{% url 'handleInventory' 'add' %}" name="addInventoryForm" id="addInventoryForm">
                {% csrf_token %}
                <div class="p-3 inventoryModalForm">
                    <input type="hidden" name="projectId" value="{{ project.id }}">
                    {{ inventoryForm.itemName }}
                    {{ inventoryForm.itemDescription }}
                    <label for="id_itemQty" class="font-bold">Amount:</label>
                    {{ inventoryForm.itemQty }}
                    {{ inventoryForm.itemUnit }} <br>
                    <label for="id_itemLimitAlert" class="font-bold">Restock Alert:</label>
                    {{ inventoryForm.itemLimitAlert }}
                </div>
            </form>
            <div class="flex justify-end items-center w-100 border-t p-3">
                <button class="bg-red-400 hover:bg-red-500 px-3 py-1 rounded text-white mr-1 close-modal">Back</button>
                <button class="bg-sky-400 hover:bg-sky-500 px-3 py-1 rounded text-white add-modal">Add</button>
            </div>
        </div>
    </div>
    <div id="tasksAndInventorySection">
        <span id="tasksContainer">
            <h3 class="mb-1">Tasks</h3>
            {% if project.hasTasks %}
                {% if tasks %}
                    {% for task in tasks %}
                    {% if task.taskCompletion == False %}
            <div class="taskInstancesContainer" id="taskInstancesContainer{{ task.id }}">
                <form method="POST" action="{% url 'handleTasks' 'complete' %}" name="completeTaskForm{{ task.id }}" id="{{ task.id }}">
                        {% csrf_token %}
                        {% for form in taskForms %}
                            {% if form.instance.id == task.id %}   
                                <input type="hidden" value="{{ task.id }}" name="hidTaskId">
                                {{ form.taskCompletion }}
                            {% endif %}
                        {% endfor %}
                </form>
                <span class="inline-block font-bold text-base">{{ task.taskName }}</span>
                <span class="inline-block font-medium italic text-sm"><b>Due in:</b> {{ task.taskDeadline }}</span>
                <span class="taskDeleteBtns">
                    <i class="fa-solid fa-xmark cursor-pointer hover:text-sky-600" data-pk="{{ task.id }}" title="Remove">{% csrf_token %}</i>
                </span>     
            </div>
                    {% endif %}
                    {% endfor %}
                    <p class="font-bold">Completed</p>
                    <hr class="mb-2">
                    {% for task in tasks %}
                    {% if task.taskCompletion == True %}
            <div class="taskInstancesContainer" id="taskInstancesContainer{{ task.id }}">
                <form method="POST" action="{% url 'handleTasks' 'complete' %}" name="completeTaskForm{{ task.id }}" id="{{ task.id }}">
                        {% csrf_token %}
                        {% for form in taskForms %}
                            {% if form.instance.id == task.id %}    
                                <input type="hidden" value="{{ task.id }}" name="hidTaskId">
                                {{ form.taskCompletion }}    
                            {% endif %}
                        {% endfor %}
                </form>
                <span class="inline-block font-bold text-lg">{{ task.taskName }}</span>
                <span class="inline-block font-medium italic text-sm"><b>Due in:</b> {{ task.taskDeadline }}</span>
                <span style="text-decoration: none;" class="taskDeleteBtns">
                    <i class="fa-solid fa-xmark cursor-pointer hover:text-sky-600" data-pk="{{ task.id }}" title="Remove">{% csrf_token %}</i>
                </span> 
            </div>
                    {% endif %}
                    {% endfor %}
            <button type="button" class="addTaskButton inline-block rounded bg-sky-200 px-6 pb-2 pt-2.5 text-xs font-medium uppercase leading-normal 
            text-black shadow-[0_4px_9px_-4px_#3b71ca] transition duration-150 ease-in-out hover:bg-sky-300 max-w-s self-center">
                + Add Task
            </button>
                {% else %}
            <p>Currently, there are no tasks.</p>
            <button type="button" class="addTaskButton inline-block rounded bg-sky-200 px-6 pb-2 pt-2.5 text-xs font-medium uppercase leading-normal 
            text-black shadow-[0_4px_9px_-4px_#3b71ca] transition duration-150 ease-in-out hover:bg-sky-300 max-w-s self-center">
                + Add Task
            </button>
                {% endif %}
            {% else %}
            <p>Tasks are <b>disabled</b> of this project.</p>
            <!-- Add another conditional here for owner of project (enable/disable button) -->
            <p>Request project owner to enable this functionality.</p>
            {% endif %}
        </span>
        <span id="inventoryContainer">
            <h3>Inventory</h3>
            {% if project.hasInventory %}
                {% if inventory %}
                    {% for inventoryItem in inventory %}
                        {% if inventoryItem.itemQty > 0 and inventoryItem.itemLimitAlert == None or inventoryItem.itemQty > inventoryItem.itemLimitAlert and inventoryItem.itemLimitAlert != None %}
            <div class="inventoryInstancesContainer relative" id="inventoryInstanceContainer{{ inventoryItem.id }}">
                <span class="ml-1 pr-2 inline-block">
                    <a href="#" class="increment-btn"><p><i class="fa-regular fa-square-plus" data-pk="{{ inventoryItem.id }}">{% csrf_token %}</i></p></a>
                    <a href="#" class="decrement-btn"><p><i class="fa-regular fa-square-minus" data-pk="{{ inventoryItem.id }}">{% csrf_token %}</i></p></a>
                </span>
                <span class="inline-block font-bold">{{ inventoryItem.itemName }}</span>
                <span class="inline-block font-medium italic text-sm mr-3">
                    <span class="inline-block" id="qty{{inventoryItem.id}}">{{inventoryItem.itemQty}}</span> 
                    {{inventoryItem.get_itemUnit_display}}
                </span>
                <span class="flex flex-col">
                    <span class="inventoryDeleteBtns">
                        <i class="fa-solid fa-xmark cursor-pointer hover:text-sky-600" data-pk="{{ inventoryItem.id }}" title="Remove">{% csrf_token %}</i>
                    </span>
                    <span class="inventoryEditBtns">
                        <i class="fa-regular fa-pen-to-square hover:text-sky-600 cursor-pointer" data-pk="{{ inventoryItem.id }}" title="Edit">{% csrf_token %}</i>
                    </span>
                </span>
            </div> 
                        {% endif %}
                    {% endfor %}
            <p class="font-bold">Restock</p>
            <hr class="mb-2">
                    {% for inventoryItem in inventory %}
                        {% if inventoryItem.itemQty == 0 or inventoryItem.itemQty <= inventoryItem.itemLimitAlert %}
            <div class="inventoryInstancesContainer relative opacity-50" id="inventoryInstanceRestockContainer{{ inventoryItem.id }}">
                <span class="ml-1 pr-2 inline-block">
                    <a href="#" class="increment-btn"><p><i class="fa-regular fa-square-plus" data-pk="{{ inventoryItem.id }}">{% csrf_token %}</i></p></a>
                    <a href="#" class="decrement-btn"><p><i class="fa-regular fa-square-minus" data-pk="{{ inventoryItem.id }}">{% csrf_token %}</i></p></a>
                </span>
                <span class="inline-block font-bold">{{ inventoryItem.itemName }}</span>
                <span class="inline-block font-medium italic text-sm mr-3">
                    <span class="inline-block" id="qty{{inventoryItem.id}}">{{inventoryItem.itemQty}}</span> 
                    {{inventoryItem.get_itemUnit_display}}
                </span>
                <span class="flex flex-col">
                    <span class="inventoryDeleteBtns">
                        <i class="fa-solid fa-xmark cursor-pointer hover:text-sky-600" data-pk="{{ inventoryItem.id }}" title="Remove">{% csrf_token %}</i>
                    </span>
                    <span class="inventoryEditBtns">
                        <i class="fa-regular fa-pen-to-square hover:text-sky-600 cursor-pointer" data-pk="{{ inventoryItem.id }}" title="Edit">{% csrf_token %}</i>
                    </span>
                </span>
            </div> 
                        {% endif %}
                    {% endfor %}
            <button type="button" class="addInventoryButton inline-block rounded bg-sky-200 px-6 pb-2 pt-2.5 text-xs font-medium uppercase leading-normal 
            text-black shadow-[0_4px_9px_-4px_#3b71ca] transition duration-150 ease-in-out hover:bg-sky-300 max-w-s self-center">
                + Add Inventory
            </button>
                {% else %}
            <p>Currently, there is no inventory.</p>
            <button type="button" class="addInventoryButton inline-block rounded bg-sky-200 px-6 pb-2 pt-2.5 text-xs font-medium uppercase leading-normal 
            text-black shadow-[0_4px_9px_-4px_#3b71ca] transition duration-150 ease-in-out hover:bg-sky-300 max-w-s self-center">
                + Add Inventory
            </button>
                {% endif %}
            {% else %}
            <p>Inventory is <b>disabled</b> of this project.</p>
            <p>Request project owner to enable this functionality.</p>
            {% endif %}
        </span>
    </div>
</div>
<div id="commentsProjectPageContainer">
    <form action="{% url 'projectPage' project.id %}" method="POST" class="commentForm">
        {% csrf_token %}
        {{ form.comment|safe }}
        <input class="inline-block rounded-full border-2 border-sky
        px-6 pt-2 pb-[8px] mt-2 mb-2 text-xs font-medium uppercase leading-normal 
        mb-1 hover:border-sky-600 cursor-pointer"
        id="commentButton" type="submit" value="Comment" name="commentBtn">
        {% for comment in comments %}
        <div class="bg-gray-100 m-2 border rounded-2xl px-5 py-2">
            <p style="display:inline-block" class="font-medium py-1">{{ comment.user }}</p>
            <i id="{{comment.id}}" class="fa-solid fa-xmark cursor-pointer deleteButton" style="float: right;"></i> <!--TODO: Delete Comment Button-->
            <li class="list-none text-base mb-2">{{ comment.comment }}</li>
            <p class="text-gray-600 text-xs py-2">{{ comment.date }} | {{ comment.time }}</p>
        </div>
        {% endfor %}
    </form>
    
</div>
{% endblock %}